swagger: '2.0'
info:
  description: Loan Api Documentation
  version: 1.12.3
  title: Patika Loan Swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8080
basePath: /
tags:
  - name: credit-controller
    description: Credit Controller
  - name: customer-controller
    description: Customer Controller
paths:
  /credit:
    post:
      tags:
        - credit-controller
      summary: Method to add a credit
      operationId: addCreditUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: credit
          description: credit
          required: true
          schema:
            $ref: '#/definitions/Credit Api Model Documentation'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CreditDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /credit/{tcId}:
    get:
      tags:
        - credit-controller
      summary: Method to retrieve all credits for a customer
      operationId: getCreditsByTcIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: tcId
          in: path
          description: tcId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CreditDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /customer:
    post:
      tags:
        - customer-controller
      summary: Method to add a new customer
      operationId: addCustomerUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: customer
          description: customer
          required: true
          schema:
            $ref: '#/definitions/Customer Api Model Documentation'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CustomerDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /customer/credit/{tcId}:
    get:
      tags:
        - customer-controller
      summary: Method to check credit result for a customer with tc id
      operationId: creditCheckUsingGET
      produces:
        - '*/*'
      parameters:
        - name: tcId
          in: path
          description: tcId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /customer/{tcId}:
    delete:
      tags:
        - customer-controller
      summary: Method to delete an exist customer
      operationId: deleteCustomerUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: tcId
          in: path
          description: tcId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
    patch:
      tags:
        - customer-controller
      summary: Method to update an exist customer
      operationId: updateCustomerUsingPATCH
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: customer
          description: customer
          required: true
          schema:
            $ref: '#/definitions/Customer Api Model Documentation'
        - name: tcId
          in: path
          description: tcId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CustomerDto'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  Credit Api Model Documentation:
    type: object
    properties:
      amount:
        type: integer
        format: int32
        description: Amount field for credit object
      creditId:
        type: integer
        format: int32
        description: Unique id field for credit object
      customer:
        description: Customer field for credit object
        $ref: '#/definitions/Customer Api Model Documentation'
      status:
        type: string
        description: Credit status field for credit object
        enum:
          - APPROVAL
          - DENIED
    title: Credit Api Model Documentation
    description: Model
  CreditDto:
    type: object
    properties:
      amount:
        type: integer
        format: int32
      creditId:
        type: integer
        format: int32
      status:
        type: string
        enum:
          - APPROVAL
          - DENIED
      tcId:
        type: integer
        format: int64
    title: CreditDto
  Customer Api Model Documentation:
    type: object
    properties:
      creditNote:
        type: integer
        format: int32
        description: Credit Note field for Customer object
      name:
        type: string
        description: 'Name field of Customer object '
      phoneNumber:
        type: string
        description: Phone Number field for Customer object
      salary:
        type: integer
        format: int32
        description: Salary field for Customer object
      surname:
        type: string
        description: Surname field for Customer object
      tcId:
        type: integer
        format: int64
        description: Unique id field for Customer object
    title: Customer Api Model Documentation
    description: Model
  CustomerDto:
    type: object
    properties:
      creditNote:
        type: integer
        format: int32
      name:
        type: string
      phoneNumber:
        type: string
      salary:
        type: integer
        format: int32
      surname:
        type: string
      tcId:
        type: integer
        format: int64
    title: CustomerDto
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
